list =['abcd',"kamal",2.23,'john',70.2]
tinylist = [123,'john']
section =['A']
print( list)
print( list [0])
print( list[1:3])
print( list[2:])
print( tinylist * 2)
print(list + tinylist)
print(list[-1])
print("john" in list)
print("dhfh" in list)
print("abcd"not in list)
print("dhfh"not in list)
print(len(list))
list.append("yemon")
print(list)
list.insert(2,"5.56")
print(list)
list.remove("john")
print(list)
sub =[20,4,56]
sub.sort()
print(sub)
sub.reverse()
print(sub)
sub.pop()
print(sub)
sub1=sub.copy()
print(sub)
sub.clear()
print(sub)
sub2=[56,45,21,87,45,45]
pos=sub2.index(87)
print(pos)
subject =[20,10,4,55,4,1,4,4]
pos=subject.count(4)
print(pos)